### PR TITLE
[Add] Linux release x86_64 musl in workflows

### PR DESCRIPTION
**Pull request by inceabdullah**
I've added a Linux release in GitHub Actions. Please review.

### CODE REVIEW

**Comment by M0dEx** [comment]
Hi!

Thanks a lot for the contribution.

Would it be possible to do this in the `release` workflow, instead of the `rust` workflow?

**Comment by inceabdullah** [comment]
> Hi!
> 
> Thanks a lot for the contribution.
> 
> Would it be possible to do this in the `release` workflow, instead of the `rust` workflow?

make sense

**Comment by inceabdullah** [comment]
I've move it.

**Comment by M0dEx** [comment]
Closed in favour of #16.

**Pull request closed without merging**
